# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3835e97ce577083af29697105e6c02a2124cfbbd77c3aa2c8ebd2b95c0a6227ee1817484067926fbbc9bd09e67ddf2d43c563f124babf5b76fadd8125c59536

test:
  secret_key_base: 6efb0be5deea85a04a9dca49a5b1b8bcb02a5d3fcbe90413a2ea456dce9f387d9c8479e33b9bb0a4bb2530f534ef773ad8b78d294eb79de170b76f98d6a070ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
